import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import React from 'react'

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>WIP</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1> HAHA This is a work in progress. Come back later 😅 </h1>
      </main>

    </div>
  )
}

export default Home
